apiVersion: v1
kind: Service
metadata:
  name: simple-rgwebapi-service
spec:
  selector:
    app: simple-rgwebapi-pod-v4
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer